// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: app/grpc/proto/iscollect/iscollect.proto

package iscollect

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsCollectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  uint64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	EventId uint64 `protobuf:"varint,2,opt,name=EventId,proto3" json:"EventId,omitempty"`
}

func (x *IsCollectRequest) Reset() {
	*x = IsCollectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_proto_iscollect_iscollect_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsCollectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsCollectRequest) ProtoMessage() {}

func (x *IsCollectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_proto_iscollect_iscollect_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsCollectRequest.ProtoReflect.Descriptor instead.
func (*IsCollectRequest) Descriptor() ([]byte, []int) {
	return file_app_grpc_proto_iscollect_iscollect_proto_rawDescGZIP(), []int{0}
}

func (x *IsCollectRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IsCollectRequest) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type IsCollectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsCollect bool `protobuf:"varint,1,opt,name=IsCollect,proto3" json:"IsCollect,omitempty"`
}

func (x *IsCollectResponse) Reset() {
	*x = IsCollectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_proto_iscollect_iscollect_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsCollectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsCollectResponse) ProtoMessage() {}

func (x *IsCollectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_proto_iscollect_iscollect_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsCollectResponse.ProtoReflect.Descriptor instead.
func (*IsCollectResponse) Descriptor() ([]byte, []int) {
	return file_app_grpc_proto_iscollect_iscollect_proto_rawDescGZIP(), []int{1}
}

func (x *IsCollectResponse) GetIsCollect() bool {
	if x != nil {
		return x.IsCollect
	}
	return false
}

var File_app_grpc_proto_iscollect_iscollect_proto protoreflect.FileDescriptor

var file_app_grpc_proto_iscollect_iscollect_proto_rawDesc = []byte{
	0x0a, 0x28, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x69, 0x73, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x2f, 0x69, 0x73, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63,
	0x22, 0x44, 0x0a, 0x10, 0x49, 0x73, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x11, 0x49, 0x73, 0x43, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x49,
	0x73, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x49, 0x73, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x32, 0x55, 0x0a, 0x10, 0x49, 0x73, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x49, 0x73, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x12, 0x16, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x73, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x73, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x1f, 0x5a, 0x1d, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x73, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_grpc_proto_iscollect_iscollect_proto_rawDescOnce sync.Once
	file_app_grpc_proto_iscollect_iscollect_proto_rawDescData = file_app_grpc_proto_iscollect_iscollect_proto_rawDesc
)

func file_app_grpc_proto_iscollect_iscollect_proto_rawDescGZIP() []byte {
	file_app_grpc_proto_iscollect_iscollect_proto_rawDescOnce.Do(func() {
		file_app_grpc_proto_iscollect_iscollect_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_grpc_proto_iscollect_iscollect_proto_rawDescData)
	})
	return file_app_grpc_proto_iscollect_iscollect_proto_rawDescData
}

var file_app_grpc_proto_iscollect_iscollect_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_grpc_proto_iscollect_iscollect_proto_goTypes = []interface{}{
	(*IsCollectRequest)(nil),  // 0: grpc.IsCollectRequest
	(*IsCollectResponse)(nil), // 1: grpc.IsCollectResponse
}
var file_app_grpc_proto_iscollect_iscollect_proto_depIdxs = []int32{
	0, // 0: grpc.IsCollectService.GetIsCollect:input_type -> grpc.IsCollectRequest
	1, // 1: grpc.IsCollectService.GetIsCollect:output_type -> grpc.IsCollectResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_grpc_proto_iscollect_iscollect_proto_init() }
func file_app_grpc_proto_iscollect_iscollect_proto_init() {
	if File_app_grpc_proto_iscollect_iscollect_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_grpc_proto_iscollect_iscollect_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsCollectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_proto_iscollect_iscollect_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsCollectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_grpc_proto_iscollect_iscollect_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_grpc_proto_iscollect_iscollect_proto_goTypes,
		DependencyIndexes: file_app_grpc_proto_iscollect_iscollect_proto_depIdxs,
		MessageInfos:      file_app_grpc_proto_iscollect_iscollect_proto_msgTypes,
	}.Build()
	File_app_grpc_proto_iscollect_iscollect_proto = out.File
	file_app_grpc_proto_iscollect_iscollect_proto_rawDesc = nil
	file_app_grpc_proto_iscollect_iscollect_proto_goTypes = nil
	file_app_grpc_proto_iscollect_iscollect_proto_depIdxs = nil
}
