#config
app:
  name: 'map'
  version: '0.0.1'
  port: :8157
  grpc_port: :8158
  
#map database
database:
  host: '158.180.71.117'
  port: 5432
  database: 'map'
  rw:
    user: 'map_rw'
    password: 'rladndwo3'
  ro:
    user: 'map_ro'
    password: 'dltngus3'