// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: app/grpc/proto/patient/patient.proto

// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative ./app/grpc/proto/patient/patient.proto

package patient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PatientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PatientNo int64 `protobuf:"varint,1,opt,name=patientNo,proto3" json:"patientNo,omitempty"`
}

func (x *PatientRequest) Reset() {
	*x = PatientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_proto_patient_patient_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientRequest) ProtoMessage() {}

func (x *PatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_proto_patient_patient_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientRequest.ProtoReflect.Descriptor instead.
func (*PatientRequest) Descriptor() ([]byte, []int) {
	return file_app_grpc_proto_patient_patient_proto_rawDescGZIP(), []int{0}
}

func (x *PatientRequest) GetPatientNo() int64 {
	if x != nil {
		return x.PatientNo
	}
	return 0
}

type PatientResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PatientNo int64  `protobuf:"varint,1,opt,name=patientNo,proto3" json:"patientNo,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age       uint64 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	BirthDate string `protobuf:"bytes,4,opt,name=birthDate,proto3" json:"birthDate,omitempty"`
	Gender    string `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Alived    bool   `protobuf:"varint,6,opt,name=alived,proto3" json:"alived,omitempty"`
}

func (x *PatientResponse) Reset() {
	*x = PatientResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_proto_patient_patient_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientResponse) ProtoMessage() {}

func (x *PatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_proto_patient_patient_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientResponse.ProtoReflect.Descriptor instead.
func (*PatientResponse) Descriptor() ([]byte, []int) {
	return file_app_grpc_proto_patient_patient_proto_rawDescGZIP(), []int{1}
}

func (x *PatientResponse) GetPatientNo() int64 {
	if x != nil {
		return x.PatientNo
	}
	return 0
}

func (x *PatientResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PatientResponse) GetAge() uint64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *PatientResponse) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *PatientResponse) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *PatientResponse) GetAlived() bool {
	if x != nil {
		return x.Alived
	}
	return false
}

var File_app_grpc_proto_patient_patient_proto protoreflect.FileDescriptor

var file_app_grpc_proto_patient_patient_proto_rawDesc = []byte{
	0x0a, 0x24, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x2e, 0x0a, 0x0e,
	0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x22, 0xa3, 0x01, 0x0a,
	0x0f, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x03, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x44, 0x61, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x44, 0x61,
	0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6c,
	0x69, 0x76, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x6c, 0x69, 0x76,
	0x65, 0x64, 0x32, 0x51, 0x0a, 0x0e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x74, 0x69, 0x65,
	0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x61,
	0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1d, 0x5a, 0x1b, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x61, 0x70,
	0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x74,
	0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_grpc_proto_patient_patient_proto_rawDescOnce sync.Once
	file_app_grpc_proto_patient_patient_proto_rawDescData = file_app_grpc_proto_patient_patient_proto_rawDesc
)

func file_app_grpc_proto_patient_patient_proto_rawDescGZIP() []byte {
	file_app_grpc_proto_patient_patient_proto_rawDescOnce.Do(func() {
		file_app_grpc_proto_patient_patient_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_grpc_proto_patient_patient_proto_rawDescData)
	})
	return file_app_grpc_proto_patient_patient_proto_rawDescData
}

var file_app_grpc_proto_patient_patient_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_grpc_proto_patient_patient_proto_goTypes = []interface{}{
	(*PatientRequest)(nil),  // 0: grpc.PatientRequest
	(*PatientResponse)(nil), // 1: grpc.PatientResponse
}
var file_app_grpc_proto_patient_patient_proto_depIdxs = []int32{
	0, // 0: grpc.PatientService.GetPatientById:input_type -> grpc.PatientRequest
	1, // 1: grpc.PatientService.GetPatientById:output_type -> grpc.PatientResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_grpc_proto_patient_patient_proto_init() }
func file_app_grpc_proto_patient_patient_proto_init() {
	if File_app_grpc_proto_patient_patient_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_grpc_proto_patient_patient_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_proto_patient_patient_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatientResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_grpc_proto_patient_patient_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_grpc_proto_patient_patient_proto_goTypes,
		DependencyIndexes: file_app_grpc_proto_patient_patient_proto_depIdxs,
		MessageInfos:      file_app_grpc_proto_patient_patient_proto_msgTypes,
	}.Build()
	File_app_grpc_proto_patient_patient_proto = out.File
	file_app_grpc_proto_patient_patient_proto_rawDesc = nil
	file_app_grpc_proto_patient_patient_proto_goTypes = nil
	file_app_grpc_proto_patient_patient_proto_depIdxs = nil
}
