// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.0
// source: app/grpc/proto/dex/dex.proto

package dex

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DexEventServiceClient is the client API for DexEventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DexEventServiceClient interface {
	FindDexEvent(ctx context.Context, in *DexEventRequest, opts ...grpc.CallOption) (*DexEventResponse, error)
	GetRate(ctx context.Context, in *RateRequest, opts ...grpc.CallOption) (*RateResponse, error)
}

type dexEventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDexEventServiceClient(cc grpc.ClientConnInterface) DexEventServiceClient {
	return &dexEventServiceClient{cc}
}

func (c *dexEventServiceClient) FindDexEvent(ctx context.Context, in *DexEventRequest, opts ...grpc.CallOption) (*DexEventResponse, error) {
	out := new(DexEventResponse)
	err := c.cc.Invoke(ctx, "/grpc.DexEventService/FindDexEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexEventServiceClient) GetRate(ctx context.Context, in *RateRequest, opts ...grpc.CallOption) (*RateResponse, error) {
	out := new(RateResponse)
	err := c.cc.Invoke(ctx, "/grpc.DexEventService/GetRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DexEventServiceServer is the server API for DexEventService service.
// All implementations must embed UnimplementedDexEventServiceServer
// for forward compatibility
type DexEventServiceServer interface {
	FindDexEvent(context.Context, *DexEventRequest) (*DexEventResponse, error)
	GetRate(context.Context, *RateRequest) (*RateResponse, error)
	mustEmbedUnimplementedDexEventServiceServer()
}

// UnimplementedDexEventServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDexEventServiceServer struct {
}

func (UnimplementedDexEventServiceServer) FindDexEvent(context.Context, *DexEventRequest) (*DexEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindDexEvent not implemented")
}
func (UnimplementedDexEventServiceServer) GetRate(context.Context, *RateRequest) (*RateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRate not implemented")
}
func (UnimplementedDexEventServiceServer) mustEmbedUnimplementedDexEventServiceServer() {}

// UnsafeDexEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DexEventServiceServer will
// result in compilation errors.
type UnsafeDexEventServiceServer interface {
	mustEmbedUnimplementedDexEventServiceServer()
}

func RegisterDexEventServiceServer(s grpc.ServiceRegistrar, srv DexEventServiceServer) {
	s.RegisterService(&DexEventService_ServiceDesc, srv)
}

func _DexEventService_FindDexEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DexEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexEventServiceServer).FindDexEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.DexEventService/FindDexEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexEventServiceServer).FindDexEvent(ctx, req.(*DexEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DexEventService_GetRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexEventServiceServer).GetRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.DexEventService/GetRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexEventServiceServer).GetRate(ctx, req.(*RateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DexEventService_ServiceDesc is the grpc.ServiceDesc for DexEventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DexEventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.DexEventService",
	HandlerType: (*DexEventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindDexEvent",
			Handler:    _DexEventService_FindDexEvent_Handler,
		},
		{
			MethodName: "GetRate",
			Handler:    _DexEventService_GetRate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/grpc/proto/dex/dex.proto",
}
