// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: app/grpc/proto/dosage/dosage.proto

// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative ./app/grpc/proto/dosage/dosage.proto

package dosage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DosageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DosageNo int64 `protobuf:"varint,1,opt,name=dosageNo,proto3" json:"dosageNo,omitempty"`
}

func (x *DosageRequest) Reset() {
	*x = DosageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_proto_dosage_dosage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DosageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DosageRequest) ProtoMessage() {}

func (x *DosageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_proto_dosage_dosage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DosageRequest.ProtoReflect.Descriptor instead.
func (*DosageRequest) Descriptor() ([]byte, []int) {
	return file_app_grpc_proto_dosage_dosage_proto_rawDescGZIP(), []int{0}
}

func (x *DosageRequest) GetDosageNo() int64 {
	if x != nil {
		return x.DosageNo
	}
	return 0
}

type DosageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DosageNo int64 `protobuf:"varint,1,opt,name=dosageNo,proto3" json:"dosageNo,omitempty"`
	DrugInfo *Drug `protobuf:"bytes,2,opt,name=drugInfo,proto3" json:"drugInfo,omitempty"`
	Cycle    int64 `protobuf:"varint,3,opt,name=cycle,proto3" json:"cycle,omitempty"`
}

func (x *DosageResponse) Reset() {
	*x = DosageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_proto_dosage_dosage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DosageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DosageResponse) ProtoMessage() {}

func (x *DosageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_proto_dosage_dosage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DosageResponse.ProtoReflect.Descriptor instead.
func (*DosageResponse) Descriptor() ([]byte, []int) {
	return file_app_grpc_proto_dosage_dosage_proto_rawDescGZIP(), []int{1}
}

func (x *DosageResponse) GetDosageNo() int64 {
	if x != nil {
		return x.DosageNo
	}
	return 0
}

func (x *DosageResponse) GetDrugInfo() *Drug {
	if x != nil {
		return x.DrugInfo
	}
	return nil
}

func (x *DosageResponse) GetCycle() int64 {
	if x != nil {
		return x.Cycle
	}
	return 0
}

type Drug struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Usage       string `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	SideEffect  string `protobuf:"bytes,4,opt,name=sideEffect,proto3" json:"sideEffect,omitempty"`
	Warning     string `protobuf:"bytes,5,opt,name=warning,proto3" json:"warning,omitempty"`
	Storage     string `protobuf:"bytes,6,opt,name=storage,proto3" json:"storage,omitempty"`
	Image       string `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *Drug) Reset() {
	*x = Drug{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_proto_dosage_dosage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Drug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drug) ProtoMessage() {}

func (x *Drug) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_proto_dosage_dosage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drug.ProtoReflect.Descriptor instead.
func (*Drug) Descriptor() ([]byte, []int) {
	return file_app_grpc_proto_dosage_dosage_proto_rawDescGZIP(), []int{2}
}

func (x *Drug) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Drug) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Drug) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

func (x *Drug) GetSideEffect() string {
	if x != nil {
		return x.SideEffect
	}
	return ""
}

func (x *Drug) GetWarning() string {
	if x != nil {
		return x.Warning
	}
	return ""
}

func (x *Drug) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

func (x *Drug) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

var File_app_grpc_proto_dosage_dosage_proto protoreflect.FileDescriptor

var file_app_grpc_proto_dosage_dosage_proto_rawDesc = []byte{
	0x0a, 0x22, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x64, 0x6f, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x64, 0x6f, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x2b, 0x0a, 0x0d, 0x44, 0x6f,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x6f, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64,
	0x6f, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x22, 0x6a, 0x0a, 0x0e, 0x44, 0x6f, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x6f, 0x73,
	0x61, 0x67, 0x65, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x6f, 0x73,
	0x61, 0x67, 0x65, 0x4e, 0x6f, 0x12, 0x26, 0x0a, 0x08, 0x64, 0x72, 0x75, 0x67, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44,
	0x72, 0x75, 0x67, 0x52, 0x08, 0x64, 0x72, 0x75, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x79,
	0x63, 0x6c, 0x65, 0x22, 0xbc, 0x01, 0x0a, 0x04, 0x44, 0x72, 0x75, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x69, 0x64, 0x65,
	0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x69,
	0x64, 0x65, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x61, 0x72, 0x6e,
	0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x61, 0x72, 0x6e, 0x69,
	0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x32, 0x4d, 0x0a, 0x0d, 0x44, 0x6f, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x73, 0x61, 0x67, 0x65,
	0x42, 0x79, 0x49, 0x64, 0x12, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x6f, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x44, 0x6f, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x1c, 0x5a, 0x1a, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x6f, 0x73, 0x61, 0x67, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_grpc_proto_dosage_dosage_proto_rawDescOnce sync.Once
	file_app_grpc_proto_dosage_dosage_proto_rawDescData = file_app_grpc_proto_dosage_dosage_proto_rawDesc
)

func file_app_grpc_proto_dosage_dosage_proto_rawDescGZIP() []byte {
	file_app_grpc_proto_dosage_dosage_proto_rawDescOnce.Do(func() {
		file_app_grpc_proto_dosage_dosage_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_grpc_proto_dosage_dosage_proto_rawDescData)
	})
	return file_app_grpc_proto_dosage_dosage_proto_rawDescData
}

var file_app_grpc_proto_dosage_dosage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_app_grpc_proto_dosage_dosage_proto_goTypes = []interface{}{
	(*DosageRequest)(nil),  // 0: grpc.DosageRequest
	(*DosageResponse)(nil), // 1: grpc.DosageResponse
	(*Drug)(nil),           // 2: grpc.Drug
}
var file_app_grpc_proto_dosage_dosage_proto_depIdxs = []int32{
	2, // 0: grpc.DosageResponse.drugInfo:type_name -> grpc.Drug
	0, // 1: grpc.DosageService.GetDosageById:input_type -> grpc.DosageRequest
	1, // 2: grpc.DosageService.GetDosageById:output_type -> grpc.DosageResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_grpc_proto_dosage_dosage_proto_init() }
func file_app_grpc_proto_dosage_dosage_proto_init() {
	if File_app_grpc_proto_dosage_dosage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_grpc_proto_dosage_dosage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DosageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_proto_dosage_dosage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DosageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_proto_dosage_dosage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Drug); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_grpc_proto_dosage_dosage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_grpc_proto_dosage_dosage_proto_goTypes,
		DependencyIndexes: file_app_grpc_proto_dosage_dosage_proto_depIdxs,
		MessageInfos:      file_app_grpc_proto_dosage_dosage_proto_msgTypes,
	}.Build()
	File_app_grpc_proto_dosage_dosage_proto = out.File
	file_app_grpc_proto_dosage_dosage_proto_rawDesc = nil
	file_app_grpc_proto_dosage_dosage_proto_goTypes = nil
	file_app_grpc_proto_dosage_dosage_proto_depIdxs = nil
}
